[build]
  command = "composer install --no-dev && npm install && npm run build"
  publish = "public"

[build.environment]
  # Add any environment variables needed for your application

[context.production]
  command = "composer install --no-dev && npm install && npm run build"

[context.deploy-preview]
  command = "composer install --no-dev && npm install && npm run build"
